spring:
  security:
    user:
      name: buzz
      password: infinity
  datasource:
    generate-unique-name: false
    name: tacocloud

taco:
  orders:
    pageSize: 10


  discount:
    codes:
      abcdef: 10


---
spring:
  config:
    activate:
      on-profile: testpro
  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: testuser
    password: testpw

logging:
  level:
    tacos: WARN
  file:
    name: my.log

taco:
  orders:
    pageSize: 5


---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: devuser
    password: devpw

logging:
  level:
    tacos: DEBUG

taco:
  orders:
    pageSize: 10